name: Feature request
description: Request a new feature for godot-playfab
labels: ["feature", "request", "triage"]
body:

  - type: markdown
    attributes:
      value: |
        - Write a descriptive issue title above.
        - Search [open](https://github.com/structed/godot-playfab/issues) and [closed](https://github.com/structed/godot-playfab/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

  - type: input
    attributes:
      label: godot-playfab version
      description: >
        Specify the Git commit hash if using a development or non-official build.
        If you use a custom build, please test if your issue is reproducible in official builds too.
      placeholder: 0.3, 3041becc6
    validations:
      required: false

  - type: input
    attributes:
      label: Godot version
      description: >
        Specify the Git commit hash if using a development or non-official build.
        If you use a custom build, please test if your issue is reproducible in official builds too.
      placeholder: v4.3.stable.official [77dcf97d8]
    validations:
      required: false

  - type: input
    attributes:
      label: System information
      description: |
        Specify the OS version, and when relevant hardware information.
        For graphics-related issues, specify the GPU model, driver version, and the rendering backend (GLES2, GLES3, Vulkan).
      placeholder: Windows 11, GLES3, Intel HD Graphics 620 (27.20.100.9616)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Issue description
      description: |
        Describe your issue briefly.
        - What is the feature you are requesting?
        - Why should it be a feature of godot-playfab?
        - Could it be an example project instead?
        - Could it be a documentation update instead?

        You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
    validations:
      required: true
